apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: fdk-monitoring-services-influxdb
  name: fdk-monitoring-services-influxdb
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fdk-monitoring-services-influxdb
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fdk-monitoring-services-influxdb
    spec:
      containers:
        - env:
          - name: INFLUXDB_HTTP_AUTH_ENABLED
            value: "true"
          - name: INFLUXDB_DB
            value: "fdk"
          - name: INFLUXDB_ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: fdk-monitoring-services-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
                key: INFLUXDB_ADMIN_USER
          - name: INFLUXDB_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: fdk-monitoring-services-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
                key: INFLUXDB_ADMIN_PASSWORD
                    
          name: fdk-monitoring-services-influxdb
          image: {{ required "Missing value INFLUXDB_IMAGE_NAME" .Values.INFLUXDB_IMAGE_NAME }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8086
          resources:
            requests:
              memory: {{ required "Missing value INFLUXDB_MEMORY" .Values.INFLUXDB_MEMORY | quote }}
          livenessProbe:
            httpGet:
              path: /health
              port: 8086
            initialDelaySeconds: 20
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8086
            initialDelaySeconds: 150
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
          volumeMounts:
            - mountPath: /var/lib/influxdb
              name: fdk-monitoring-services-influxdb-claim0
      restartPolicy: Always
      volumes:
        - name: fdk-monitoring-services-influxdb-claim0
          persistentVolumeClaim:
            claimName: fdk-monitoring-services-influxdb-claim0
status: {}
