version: '3.9'

networks:
  tig-net:
    driver: bridge

volumes:
  tig-data:

services:
  influxdb:
    image: influxdb:1.8.10
    container_name: influxdb
    ports:
      - 8086:8086
    environment:
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_DB: "fdk"
      INFLUXDB_ADMIN_USER: "admin"
      INFLUXDB_ADMIN_PASSWORD: "admin"
    networks:
      - tig-net
    volumes:
      - tig-data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:8.2.5
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    networks:
      - tig-net
    volumes:
      - tig-data:/var/lib/grafana
    restart: always

  telegraf:
    image: telegraf:1.20.4
    container_name: telegraf
    ports:
      - 8125:8125/udp
    depends_on:
      - "influxdb"
    environment:
      HOST_NAME: "telegraf"
      INFLUXDB_HOST: "influxdb"
      INFLUXDB_PORT: "8086"
      DATABASE: "fdk"
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
    tty: true
    networks:
      - tig-net
    privileged: true