apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: telegraf-operator
  labels:
    app: telegraf-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: telegraf-operator
subjects:
  - kind: ServiceAccount
    name: telegraf-operator
    namespace: telegraf-operator