apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    app: fdk-monitoring-services-telegraf
  name: fdk-monitoring-services-telegraf
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  type: NodePort
  ports:
  - name: "8125"
    port: 8125
    targetPort: 8125
    protocol: UDP
  selector:
    app: fdk-monitoring-services-telegraf
status:
  loadBalancer: {}