grafana:
  ingress:
    enabled: true
    hosts: []
    annotations:
      ingress.gcp.kubernetes.io/pre-shared-cert: stjerne-fdk-digdir-no-ssl-2,stjerne-staging-fdk-digdir-no-ssl-2
      kubernetes.io/ingress.global-static-ip-name: digdir-fdk-dev-staging-prometheus-v4
