
apiVersion: v1
kind: Secret
metadata:
  name: telegraf-operator-certs
  namespace: telegraf-operator
data:
  tls.crt: {{ required "Missing value TELEGRAF_OPERATOR_TLS_CRT" .Values.TELEGRAF_OPERATOR_TLS_CRT }}
  tls.key: {{ required "Missing value TELEGRAF_OPERATOR_TLS_KEY" .Values.TELEGRAF_OPERATOR_TLS_KEY }}
type: kubernetes.io/tls
---
apiVersion: v1
kind: Secret
metadata:
  name: telegraf-operator-classes
  namespace: telegraf-operator
stringData:
  # basic classes that can be used to develop telegraf-operator ; these classes
  # report to InfluxDB v1 in same cluster as well as to stdout for convenience
  fdk.service: |+
    [agent]
      flush_interval = "15s"
      interval = "15s"
      debug = false
    [[outputs.influxdb]]
      database = "telegraf"
      retention_policy = "365_days"
      urls = [ "http://fdk-monitoring-services-influxdb:8086" ]
      username = {{ required "Missing value INFLUXDB_ADMIN_USER" .Values.INFLUXDB_ADMIN_USER | quote }}
      password = {{ required "Missing value INFLUXDB_ADMIN_PASSWORD" .Values.INFLUXDB_ADMIN_PASSWORD | quote }}
    [global_tags]
      hostname = "$HOSTNAME"
      nodename = "$NODENAME"
      namespace = "$NAMESPACE"
      type = "app"