apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: telegraf-operator
  namespace: telegraf-operator
  labels:
    fdk.service: telegraf-operator
webhooks:
  - name: telegraf.influxdata.com
    objectSelector:
      matchLabels:
        controller: telegraf-operator
    admissionReviewVersions: ["v1"]
    sideEffects: None
    clientConfig:
      service:
        name: telegraf-operator
        namespace: telegraf-operator
        path: "/mutate-v1-pod"
      caBundle: {{ required "Missing value TELEGRAF_OPERATOR_CA_BUNDLE" .Values.TELEGRAF_OPERATOR_CA_BUNDLE }}
    rules:
      - operations: ["CREATE", "DELETE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["pods"]
    failurePolicy: Ignore
    reinvocationPolicy: IfNeeded