apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    app: fdk-monitoring-services-grafana
  name: fdk-monitoring-services-grafana
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  type: NodePort
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    app: fdk-monitoring-services-grafana
status:
  loadBalancer: {}