kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  creationTimestamp: null
  labels:
    app: fdk-monitoring-services-grafana
  name: fdk-monitoring-services-grafana-claim0
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  storageClassName: ""
  volumeName: {{ required "Missing value GRAFANA_VOLUMENAME" .Values.GRAFANA_VOLUMENAME }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ required "Missing value GRAFANA_STORAGESIZE" .Values.GRAFANA_STORAGESIZE | quote }}
status: {}

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ required "Missing value GRAFANA_VOLUMENAME" .Values.GRAFANA_VOLUMENAME }}
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  storageClassName: ""
  capacity:
    storage: {{ required "Missing value GRAFANA_STORAGESIZE" .Values.GRAFANA_STORAGESIZE | quote }}
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: {{ required "Missing value GRAFANA_VOLUMENAME" .Values.GRAFANA_VOLUMENAME }}
    fsType: ext4
