apiVersion: v1
appVersion: "1.0"
description: FDK Monitoring Services - Telegraf Operator
name: telegraf-operator
version: 0.1.0
home: https://github.com/Informasjonsforvaltning/fdk-monitoring-services